

select * from project limit 20

-- q1 what is the total revenew generated by male vs female in the excel data

select gender,
sum(purchase_amount) as revenue

from project
group by gender

-- Q2 which customer used a discount but still spent more than the average purchase amount?"
-- answer
select customer_id, purchase_amount
from project
where discount_applied = 'yes' and purchase_amount >= (select avg (purchase_amount) from project)

-- Q3 WHICH ARE THE TOP 5 PRODECTS WITH THE HIGHEST AVERAGE REVIEW RATING
-- A
SELECT Item_Purchased,
AVG(Review_Rating) AS avg_rating
FROM project
GROUP BY Item_Purchased
ORDER BY avg_rating DESC
LIMIT 10;
-- Q4 COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS
SELECT shipping_type,
avg(purchase_amount)as avg_purchase
from project
group by shipping_type;
-- Q5 DO SUBSCRIBED CUSTOMER SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE
-- BETWEEN SUBSCRIBERS AND NON SUBSCRIBERS
SELECT subscription_status,
COUNT (customer_id) as total_customers,
AVG (purchase_amount) as avg_sent,
sum (purchase_amount) as total_revenue
from project
group by (subscription_status)
order by total_revenue , avg_sent desc;

-- how many menbers are taken a subscription 
select count (customer_id) as total_subscribed
from project
where subscription_status = 'yes';

SELECT customer_id
FROM project
WHERE subscription_status = 'Yes';

-- Q6 which 5 products have the highest percentage of with discounts applied?
select item_purchased,
sum(case when discount_applied = 'yes' then 1 else 0 end )/count(*) * 100,2 as discount_rate
from project 
group by item_purchased
order by discount_rate
limit 5; 

-- second code
SELECT item_purchased,
ROUND(
    SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) 
    * 100.0 / COUNT(*), 2
) AS discount_rate
FROM project
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Q7 SEGMENT CUSTOMER INTO NEW , RETURNING , AND LOYAL BASED ON THEIR TOTAL 
-- TOTAL NUMBER OF PREVIOUS  PURCHASE, AND SHOW THE COUNT OF EACH SEGMENT
WITH customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases = 1 THEN 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from project
)

select customer_segment, count (*) as "Number of customers"

from customer_type
group by customer_segment

-- Q8 WHAT ARE THE TOP 3 MOST PRUCHASED PRODUCT WITH IN EACH CATOGARY?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count (customer_id)desc )as item_rank
group by category, item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3
-- correct code down 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM project
    GROUP BY category, item_purchased
),

ranked_items AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)

SELECT category, item_purchased, total_orders, item_rank
FROM ranked_items
WHERE item_rank <= 3;

--Q9 are the customer who are the repeated to buyers then 5 prevent purchase also to likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from project
where previous_purchases > 5
group by subscription_status


-- Q10 what are the revenue contribution of each age group 

select age_group,
sum(purchase_amount) as total_revenue
from project 
group by age_group
order by total_revenue desc;




